// Tier 1: the bundled catalog, generated by `python -m tools.catalog` and committed.
// Always present, works offline, and is why an empty results screen is structurally impossible.
//
// Parsed once at app startup — ~300 recipes costs nothing measurable and
// saves re-validating on every screen transition.

import Foundation

struct VocabularyEntry: Codable {
    let id: String
    let displayName: String
    let allergenGroups: [String]
    let isStaple: Bool
}

/// Tier 1 bundled catalog. Never empty at runtime — a build with an empty
/// recipes.json is a build error caught in CI, not a runtime edge case.
let tier1Catalog: [Recipe] = {
    guard
        let url  = Bundle.main.url(forResource: "recipes", withExtension: "json"),
        let data = try? Data(contentsOf: url),
        let raw  = try? JSONDecoder().decode([RawCatalogRecipe].self, from: data)
    else {
        assertionFailure("recipes.json missing or malformed — add it to the app bundle.")
        return []
    }
    return toCatalog(from: raw)
}()

/// The canonical ingredient vocabulary — the shared language between the
/// vision pipeline, the pantry, and the decision engine.
let ingredientVocabulary: [VocabularyEntry] = {
    guard
        let url  = Bundle.main.url(forResource: "ingredients", withExtension: "json"),
        let data = try? Data(contentsOf: url),
        let entries = try? JSONDecoder().decode([VocabularyEntry].self, from: data)
    else {
        assertionFailure("ingredients.json missing or malformed — add it to the app bundle.")
        return []
    }
    return entries
}()

private let vocabularyById: [String: VocabularyEntry] =
    Dictionary(uniqueKeysWithValues: ingredientVocabulary.map { ($0.id, $0) })

func lookupIngredient(_ id: String) -> VocabularyEntry? {
    vocabularyById[id]
}

/// Pre-populated on first run so a brand-new pantry is not empty.
let stapleIngredientIds: [String] = ingredientVocabulary
    .filter { $0.isStaple }
    .map { $0.id }
