// @ts-check
import js from '@eslint/js';
import reactNativeA11y from 'eslint-plugin-react-native-a11y';
import tseslint from 'typescript-eslint';

/**
 * The style guide §2.5 gate: "A missing accessibilityLabel fails CI."
 *
 * The upstream plugin validates prop VALUES but has no rule requiring a label
 * at all, so this local rule covers the missing half. It inspects raw
 * react-native touchables only — shared interactive components (PrimaryButton,
 * Chip, ...) are covered by linting their own internals.
 */
const INTERACTIVE_COMPONENTS = new Set([
  'Pressable',
  'TouchableOpacity',
  'TouchableHighlight',
  'TouchableNativeFeedback',
  'TouchableWithoutFeedback',
]);

const interactiveNeedsLabel = {
  meta: {
    type: 'problem',
    docs: { description: 'Interactive elements need accessibilityLabel' },
    schema: [],
  },
  create(context) {
    return {
      JSXOpeningElement(node) {
        if (node.name?.type !== 'JSXIdentifier') return;
        if (!INTERACTIVE_COMPONENTS.has(node.name.name)) return;

        const hasLabel = node.attributes.some(
          (attribute) =>
            attribute.type === 'JSXAttribute' &&
            (attribute.name?.name === 'accessibilityLabel' || attribute.name?.name === 'aria-label')
        );
        if (hasLabel) return;

        context.report({
          node,
          message: `<${node.name.name}> is interactive: set accessibilityLabel, or use a shared component that sets one.`,
        });
      },
    };
  },
};

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      '.pydeps/**',
      '.venv/**',
      '.expo/**',
      'dist/**',
      'web-build/**',
      'coverage/**',
      // Worktrees carry their own build output, which the bare 'dist/**' glob
      // does not reach. Linting a sibling branch's bundle fails CI on code that
      // is not even in this checkout.
      '.worktrees/**',
      // Native prebuild output -- regenerated by `expo prebuild`, never hand-edited.
      'android/**',
      'ios/**',
      // Deno runtime, not Node -- typechecked by the Supabase CLI instead.
      'supabase/functions/**',
      // Python.
      'tools/**',
      '.mypy_cache/**',
      '.ruff_cache/**',
      '.pytest_cache/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Node CLI scripts use platform globals (fetch, URL, Response) that
    // no-undef cannot infer from the module graph.
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        fetch: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
      },
    },
  },
  {
    rules: {
      // "No `any`. Use `unknown` at boundaries and narrow."
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': 'warn',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    // The one architectural rule worth defending mechanically: the engine is a
    // pure function over plain data, so it may not reach the outside world.
    files: ['src/engine/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'react',
                'react-*',
                '@/lib/*',
                '@supabase/*',
                '@tanstack/*',
                'expo*',
                'zustand',
              ],
              message:
                'src/engine/ must stay pure — no React, no I/O, no imports from src/lib/. See Technical Spec §4.1 and AGENTS.md.',
            },
          ],
        },
      ],
    },
  },
  {
    // Definition-of-Done gate (Technical Spec §7, UI/UX Spec §9): validity of
    // a11y prop values from the plugin, presence of labels from the local rule.
    files: ['app/**/*.tsx', 'src/**/*.tsx'],
    plugins: {
      'react-native-a11y': reactNativeA11y,
      'homechef-a11y': { rules: { 'interactive-needs-label': interactiveNeedsLabel } },
    },
    rules: {
      ...reactNativeA11y.configs.basic.rules,
      'homechef-a11y/interactive-needs-label': 'error',
    },
  }
);
