// Bundled catalog JSON in, engine Recipe out.
//
// The bundled file is generated by tools/catalog and committed, so it is
// trusted-ish — but parsed defensively. A single malformed record must not
// take down the whole catalog at launch.

import Foundation

private let fallbackMinutes = 30

// MARK: - Public API

/// Returns nil for anything that is not a usable recipe.
func toRecipe(from raw: RawCatalogRecipe) -> Recipe? {
    guard !raw.id.isEmpty, !raw.title.isEmpty else { return nil }

    let ingredients = toIngredients(raw.ingredients)
    // A recipe with no ingredients is a catalog defect. Admitting it would
    // drop it straight into the `ready` bucket with nothing missing.
    guard !ingredients.isEmpty else { return nil }

    let minutes: Int
    if let m = raw.totalTimeMinutes, m > 0 {
        minutes = Int(m)
    } else {
        minutes = fallbackMinutes
    }

    return Recipe(
        id: raw.id,
        title: raw.title,
        imageUrl: raw.imageUrl,
        cuisine: raw.cuisine,
        totalTimeMinutes: minutes,
        equipmentRequired: toEquipment(raw.equipmentRequired),
        dietaryTags: keepKnownDietary(raw.dietaryTags),
        ingredients: ingredients,
        instructions: raw.instructions ?? "",
        source: raw.source == "tier2" ? .tier2 : .tier1
    )
}

/// Maps a whole catalog array, skipping records that fail to parse.
func toCatalog(from raw: [RawCatalogRecipe]) -> [Recipe] {
    raw.compactMap { toRecipe(from: $0) }
}

// MARK: - Raw JSON shape (output of tools/catalog)

/// Mirrors the JSON keys produced by the Python catalog pipeline.
/// All fields are optional so a malformed entry skips rather than crashes.
struct RawCatalogRecipe: Decodable {
    let id: String
    let title: String
    let imageUrl: String?
    let cuisine: String?
    let totalTimeMinutes: Double?
    let equipmentRequired: [String]?
    let dietaryTags: [String]?
    let ingredients: [RawCatalogIngredient]?
    let instructions: String?
    let source: String?
}

struct RawCatalogIngredient: Decodable {
    let id: String
    let measure: String?
    let allergenGroups: [String]?
}

// MARK: - Private helpers

private func toIngredients(_ raw: [RawCatalogIngredient]?) -> [RecipeIngredient] {
    guard let raw else { return [] }
    return raw.compactMap { entry -> RecipeIngredient? in
        guard !entry.id.isEmpty else { return nil }
        return RecipeIngredient(
            id: entry.id,
            measure: entry.measure ?? "to taste",
            allergenGroups: entry.allergenGroups ?? []
        )
    }
}

/// `none` rather than an empty list when nothing is recognised: the engine
/// reads `none` as always-satisfied, which cannot wrongly exclude a user.
/// Silently passing an unknown appliance through would.
private func toEquipment(_ raw: [String]?) -> [Equipment] {
    guard let raw else { return [.none] }
    let known = raw.compactMap { Equipment(rawValue: $0) }
    let real  = known.filter { $0 != .none }
    return real.isEmpty ? [.none] : real
}

private func keepKnownDietary(_ raw: [String]?) -> [DietaryTag] {
    guard let raw else { return [] }
    return raw.compactMap { DietaryTag(rawValue: $0) }
}
