/**
 * Bundled catalog JSON in, engine `Recipe` out.
 *
 * The bundled file is generated by tools/catalog and committed, so it is
 * trusted-ish -- but it is still parsed defensively. A single malformed record
 * must not take down the whole catalog at launch, and `unknown` at the boundary
 * is the house rule.
 */
import { DIETARY_TAGS, EQUIPMENT } from '@/engine/types';
import { nutritionConfidenceSchema, nutritionProvenanceSchema } from '@/contracts/meal-journeys';
import { MEAL_SLOTS, type MealSlot } from '@/contracts/meal-slots';
import type { DietaryTag, Equipment, Recipe, RecipeIngredient } from '@/engine/types';

const FALLBACK_MINUTES = 30;

/** Returns `null` for anything that is not a usable recipe. */
export function toRecipe(raw: unknown): Recipe | null {
  if (!isRecord(raw)) return null;

  const id = asString(raw.id);
  const title = asString(raw.title);
  if (!id || !title) return null;

  const ingredients = toIngredients(raw.ingredients);
  // A recipe with no ingredients is a catalog defect. Admitting it would drop
  // it straight into the `ready` bucket with nothing missing.
  if (ingredients.length === 0) return null;

  const minutes = asNumber(raw.totalTimeMinutes);
  const nutrition = toNutrition(raw);

  return {
    id,
    title,
    imageUrl: asString(raw.imageUrl) ?? null,
    cuisine: normalizeCuisine(raw.cuisine),
    totalTimeMinutes: minutes !== null && minutes > 0 ? minutes : FALLBACK_MINUTES,
    equipmentRequired: toEquipment(raw.equipmentRequired),
    dietaryTags: keepKnown(raw.dietaryTags, DIETARY_TAGS),
    ingredients,
    instructions: asString(raw.instructions) ?? '',
    mealSlots: toMealSlots(raw),
    ...nutrition,
    attribution: toAttribution(raw.attribution),
    source: raw.source === 'spoonacular' ? 'spoonacular' : 'bundled',
  };
}

const CUISINE_SYNONYMS: Readonly<Record<string, string>> = {
  america: 'american',
  american: 'american',
  united_states: 'american',
  united_states_of_america: 'american',
  usa: 'american',
  us: 'american',
  britain: 'british',
  british: 'british',
  united_kingdom: 'british',
  uk: 'british',
  english: 'british',
  england: 'british',
  scottish: 'british',
  scotland: 'british',
  welsh: 'british',
  wales: 'british',
  china: 'chinese',
  chinese: 'chinese',
  france: 'french',
  french: 'french',
  india: 'indian',
  indian: 'indian',
  italy: 'italian',
  italian: 'italian',
  mexico: 'mexican',
  mexican: 'mexican',
  spain: 'spanish',
  spanish: 'spanish',
  thailand: 'thai',
  thai: 'thai',
  japan: 'japanese',
  japanese: 'japanese',
  greece: 'greek',
  greek: 'greek',
  ireland: 'irish',
  irish: 'irish',
  canada: 'canadian',
  canadian: 'canadian',
  germany: 'german',
  german: 'german',
  korea: 'korean',
  korean: 'korean',
  vietnam: 'vietnamese',
  vietnamese: 'vietnamese',
  morocco: 'moroccan',
  moroccan: 'moroccan',
  turkey: 'turkish',
};

/**
 * Normalizes free-text cuisine strings or country names into a canonical cuisine slug.
 *
 * Normalizes once at the ingestion/adaptation boundary rather than scattering UI aliases.
 */
export function normalizeCuisine(raw: unknown): string | null {
  if (typeof raw !== 'string') return null;
  const slug = raw
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  if (!slug || slug === 'any' || slug === 'none' || slug === 'null' || slug === 'unknown') {
    return null;
  }
  return CUISINE_SYNONYMS[slug] ?? slug;
}

/** Maps a whole catalog, skipping records that fail to parse. */
export function toCatalog(raw: unknown): Recipe[] {
  if (!Array.isArray(raw)) return [];
  const recipes: Recipe[] = [];
  for (const entry of raw) {
    const recipe = toRecipe(entry);
    if (recipe) recipes.push(recipe);
  }
  return recipes;
}

function toAttribution(raw: unknown): Recipe['attribution'] {
  if (!isRecord(raw)) return null;

  const sourceId = asString(raw.sourceId);
  const sourceVersion = asString(raw.sourceVersion);
  const attribution = asString(raw.attribution);
  const url = asString(raw.url);
  if (!sourceId || !sourceVersion || !attribution || !url) return null;

  return {
    sourceId,
    sourceVersion,
    sourceRecipeId: asString(raw.sourceRecipeId) ?? undefined,
    attribution,
    url,
    licenseName: asString(raw.licenseName) ?? undefined,
    licenseUrl: asString(raw.licenseUrl) ?? undefined,
  };
}

function toIngredients(raw: unknown): RecipeIngredient[] {
  if (!Array.isArray(raw)) return [];

  const ingredients: RecipeIngredient[] = [];
  for (const entry of raw) {
    if (!isRecord(entry)) continue;
    const id = asString(entry.id);
    if (!id) continue;

    ingredients.push({
      id,
      measure: asString(entry.measure) ?? 'to taste',
      allergenGroups: Array.isArray(entry.allergenGroups)
        ? entry.allergenGroups.filter((g): g is string => typeof g === 'string')
        : [],
    });
  }
  return ingredients;
}

/** Unknown metadata cannot make a claim that no equipment is required. */
function toEquipment(raw: unknown): Equipment[] {
  const known = keepKnown(raw, EQUIPMENT);
  const real = known.filter((item) => item !== 'none');
  if (real.length > 0) return real;
  return known.length > 0 ? ['none'] : ['unclassified'];
}

function keepKnown<T extends Equipment | DietaryTag>(raw: unknown, allowed: readonly T[]): T[] {
  if (!Array.isArray(raw)) return [];
  const allowedSet = new Set<string>(allowed);
  return raw.filter((value): value is T => typeof value === 'string' && allowedSet.has(value));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

function asNumber(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function asPositiveNumber(value: unknown): number | null {
  const number = asNumber(value);
  return number !== null && number > 0 ? number : null;
}

function toNutritionProvenance(raw: unknown): Recipe['nutritionProvenance'] {
  const result = nutritionProvenanceSchema.safeParse(raw);
  return result.success ? result.data : null;
}

function toNutrition(
  raw: Record<string, unknown>
): Pick<
  Recipe,
  'baseServings' | 'energyKcalPerServing' | 'nutritionProvenance' | 'nutritionConfidence'
> {
  const baseServings = asPositiveNumber(raw.baseServings);
  const nutritionProvenance = toNutritionProvenance(raw.nutritionProvenance);
  const parsedConfidence = nutritionConfidenceSchema
    .catch('unavailable')
    .parse(raw.nutritionConfidence);

  if (nutritionProvenance === null && parsedConfidence !== 'unavailable') {
    return {
      baseServings,
      energyKcalPerServing: null,
      nutritionProvenance: null,
      nutritionConfidence: 'unavailable',
    };
  }

  if (parsedConfidence === 'low' || parsedConfidence === 'unavailable') {
    return {
      baseServings,
      energyKcalPerServing: null,
      nutritionProvenance,
      nutritionConfidence: parsedConfidence,
    };
  }

  return {
    baseServings,
    energyKcalPerServing: baseServings === null ? null : asPositiveNumber(raw.energyKcalPerServing),
    nutritionProvenance,
    nutritionConfidence: parsedConfidence,
  };
}

const RECIPE_MEAL_SLOTS: Readonly<Record<string, readonly MealSlot[]>> = {
  // Breakfast items
  'hc-mw-01': ['breakfast'], // Mug Scrambled Eggs
  'hc-mw-02': ['breakfast'], // Porridge in a Bowl
  'hc-mw-09': ['breakfast'], // Cheesy Egg Mug
  'hc-mw-11': ['breakfast'], // Banana Cinnamon Oats
  'hc-mw-19': ['breakfast'], // Peanut Butter Oats
  'hc-mw-23': ['breakfast'], // Microwave Breakfast Burrito
  'hc-staple-scrambled-eggs': ['breakfast'], // Classic Scrambled Eggs
  'hc-staple-toast-jam': ['breakfast'], // Toast with Butter and Jam
  'hc-staple-cinnamon-toast': ['breakfast'], // Cinnamon Sugar Toast

  // Lunch & Dinner items (or lunch-specific)
  'hc-staple-grilled-cheese': ['lunch'], // Classic Grilled Cheese
  'hc-staple-pbj': ['lunch', 'breakfast'], // Peanut Butter and Jelly Sandwich
  'hc-staple-tuna-sandwich': ['lunch'], // Simple Tuna Salad Sandwich
  'hc-mw-22': ['lunch', 'dinner'], // Microwave Bean & Cheese Burrito
  'hc-mw-24': ['lunch', 'dinner'], // Microwave Cheese Quesadilla
  'hc-mw-21': ['lunch', 'dinner'], // Microwave Personal Pizza
  'hc-mw-05': ['lunch', 'dinner'], // Mug Mac and Cheese
  'hc-mw-25': ['lunch', 'dinner'], // Microwave Mug Mac & Cheese

  // Dinner items
  'hc-82192586fc577f61793e': ['dinner'], // Easy Spaghetti with Tomato
  'hc-48322a4046b660396285': ['lunch', 'dinner'], // Microwave Tuna Pasta
  'hc-6089840ed7a96123bbe1': ['lunch', 'dinner'], // Microwave Baked Potato
  'hc-d63529038fdd6e186d8d': ['lunch', 'dinner'], // Microwave Rice and Vegetables
  'hc-mw-03': ['lunch', 'dinner'], // Microwave Baked Potato
  'hc-mw-06': ['dinner'], // Poached Cod with Lemon
  'hc-mw-07': ['lunch', 'dinner'], // Rice and Peas Bowl
  'hc-mw-10': ['lunch', 'dinner'], // Black Bean and Sweetcorn Bowl
  'hc-mw-13': ['lunch', 'dinner'], // Herbed Couscous
  'hc-mw-15': ['dinner'], // Lemon Salmon Fillet
  'hc-mw-16': ['lunch', 'dinner'], // Spiced Lentil Bowl
  'hc-mw-17': ['lunch', 'dinner'], // Microwave Quinoa
  'hc-mw-20': ['lunch', 'dinner'], // Warm Chickpea and Tomato Bowl
  'hc-mw-26': ['lunch', 'dinner'], // Microwave Loaded Baked Potato
  'hc-mw-27': ['lunch', 'dinner'], // Microwave Steamed Rice & Veggie Bowl
};

/** Explicit validated recipe slot-suitability metadata at catalog boundary. */
export function toMealSlots(raw: Record<string, unknown>): MealSlot[] {
  const explicit = Array.isArray(raw.mealSlots)
    ? raw.mealSlots
    : Array.isArray(raw.meal_slots)
      ? raw.meal_slots
      : null;
  if (explicit) {
    const valid = explicit.filter(
      (s): s is MealSlot => typeof s === 'string' && (MEAL_SLOTS as readonly string[]).includes(s)
    );
    return MEAL_SLOTS.filter((slot) => valid.includes(slot));
  }
  const id = asString(raw.id);
  if (id && Object.hasOwn(RECIPE_MEAL_SLOTS, id)) {
    return [...RECIPE_MEAL_SLOTS[id]!];
  }
  // Unknown suitability (including desserts and side dishes) is not a verified meal.
  return [];
}
