/**
 * Bundled catalog JSON in, engine `Recipe` out.
 *
 * The bundled file is generated by tools/catalog and committed, so it is
 * trusted-ish -- but it is still parsed defensively. A single malformed record
 * must not take down the whole catalog at launch, and `unknown` at the boundary
 * is the house rule.
 */
import { DIETARY_TAGS, EQUIPMENT } from '@/engine/types';
import type { DietaryTag, Equipment, Recipe, RecipeIngredient } from '@/engine/types';

const FALLBACK_MINUTES = 30;

/** Returns `null` for anything that is not a usable recipe. */
export function toRecipe(raw: unknown): Recipe | null {
  if (!isRecord(raw)) return null;

  const id = asString(raw.id);
  const title = asString(raw.title);
  if (!id || !title) return null;

  const ingredients = toIngredients(raw.ingredients);
  // A recipe with no ingredients is a catalog defect. Admitting it would drop
  // it straight into the `ready` bucket with nothing missing.
  if (ingredients.length === 0) return null;

  const minutes = asNumber(raw.totalTimeMinutes);

  return {
    id,
    title,
    imageUrl: asString(raw.imageUrl) ?? null,
    cuisine: asString(raw.cuisine) ?? null,
    totalTimeMinutes: minutes !== null && minutes > 0 ? minutes : FALLBACK_MINUTES,
    equipmentRequired: toEquipment(raw.equipmentRequired),
    dietaryTags: keepKnown(raw.dietaryTags, DIETARY_TAGS),
    ingredients,
    instructions: asString(raw.instructions) ?? '',
    source: raw.source === 'tier2' ? 'tier2' : 'tier1',
  };
}

/** Maps a whole catalog, skipping records that fail to parse. */
export function toCatalog(raw: unknown): Recipe[] {
  if (!Array.isArray(raw)) return [];
  const recipes: Recipe[] = [];
  for (const entry of raw) {
    const recipe = toRecipe(entry);
    if (recipe) recipes.push(recipe);
  }
  return recipes;
}

function toIngredients(raw: unknown): RecipeIngredient[] {
  if (!Array.isArray(raw)) return [];

  const ingredients: RecipeIngredient[] = [];
  for (const entry of raw) {
    if (!isRecord(entry)) continue;
    const id = asString(entry.id);
    if (!id) continue;

    ingredients.push({
      id,
      measure: asString(entry.measure) ?? 'to taste',
      allergenGroups: Array.isArray(entry.allergenGroups)
        ? entry.allergenGroups.filter((g): g is string => typeof g === 'string')
        : [],
    });
  }
  return ingredients;
}

/**
 * `none` rather than an empty list when nothing is recognised: the engine reads
 * `none` as always-satisfied, which cannot wrongly exclude a user. Silently
 * passing an unknown appliance through would.
 */
function toEquipment(raw: unknown): Equipment[] {
  const known = keepKnown(raw, EQUIPMENT);
  const real = known.filter((item) => item !== 'none');
  if (real.length > 0) return real;
  return known.length > 0 ? ['none'] : ['none'];
}

function keepKnown<T extends Equipment | DietaryTag>(raw: unknown, allowed: readonly T[]): T[] {
  if (!Array.isArray(raw)) return [];
  const allowedSet = new Set<string>(allowed);
  return raw.filter((value): value is T => typeof value === 'string' && allowedSet.has(value));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

function asNumber(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}
