import recipesJson from '@/data/recipes.json';
import ingredientsJson from '@/data/ingredients.json';
import attributionsJson from '@/data/catalog-attributions.json';
import { toCatalog } from '@/lib/adapters/to-recipe';
import type { Recipe } from '@/engine/types';

export interface VocabularyEntry {
  id: string;
  displayName: string;
  allergenGroups: string[];
  isStaple: boolean;
}

export interface CatalogAttribution {
  sourceId: string;
  sourceVersion: string;
  title: string;
  url: string;
  licenseName: string;
  licenseUrl: string;
  attribution: string;
}

/** Source and license metadata for every bundled release. */
export const BUNDLED_CATALOG_ATTRIBUTIONS: readonly CatalogAttribution[] =
  attributionsJson as CatalogAttribution[];

/**
 * The bundled catalog, generated by `python -m tools.catalog` and
 * committed. Always present, works offline, and is why an empty results screen
 * is structurally impossible.
 *
 * Parsed once at module load. ~300 recipes is small enough that this costs
 * nothing measurable and saves re-validating on every render.
 */
export const BUNDLED_CATALOG: readonly Recipe[] = toCatalog(recipesJson);

/**
 * The canonical ingredient vocabulary — the shared language between the vision
 * pipeline, the pantry, and the decision engine.
 */
export const INGREDIENT_VOCABULARY: readonly VocabularyEntry[] =
  ingredientsJson as VocabularyEntry[];

const BY_ID = new Map(INGREDIENT_VOCABULARY.map((entry) => [entry.id, entry]));

export function lookupIngredient(id: string): VocabularyEntry | undefined {
  return BY_ID.get(id);
}

/** Pre-populated on first run so a brand-new pantry is not empty. */
export const STAPLE_INGREDIENT_IDS: readonly string[] = INGREDIENT_VOCABULARY.filter(
  (entry) => entry.isStaple
).map((entry) => entry.id);
